version: '3.9'

services:
  php:
    container_name: app
    build:
      context: .
      dockerfile: Docker/php/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - "./src:/usr/src/app"
    networks:
      - internal

  mysql:
    container_name: db
    image: mysql:8.0
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: Africa/Dar_es_Salaam
    networks:
      - internal


networks:
  internal:


volumes:
  mysql-data:
